console.log('before fetch')

fetch('https://www.reddit.com/r/Awww/.json')
.then(response => response.json())
.then(json => console.log(json))

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')


console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')


console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')

console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
console.log('after fetch')
